+2003-03-10  Junichi Uekawa  <dancer@debian.org> + +	* pbuilder-satisfydepends: quote some strings... trying to be pedantic + +	* pbuilder-buildpackage-funcs: unset LOGNAME for when building with +	real root privilage. +	thanks Barak Pearlmutter <bap@cs.unm.edu> + +	* pbuilder.8: document X hooks which were previously undocumented. + +	* pbuilder-user-mode-linux (BUILDING_DSC_FILE): use readlink on real existing files. +	GNU "readlink -f " exits with an exit code of 1 when the file does not +	exist, debianutils readlink did not. + +	* pbuilder-runhooks (hooks): do not call readlink here, +	  since the file may not exist. + +	* pbuilder-checkparams (USE_PKGNAME_LOGFILE): use readlink on real existing files. + +	* pbuilder-buildpackage (PACKAGENAME): use readlink on real existing files. +

diff --git a/pbuilder-user-mode-linux b/pbuilder-user-mode-linux
--- a/pbuilder-user-mode-linux
+++ b/pbuilder-user-mode-linux
@@ -202,7 +202,7 @@ while [ -n "$1" ] ; do
 	    UML_BUILDRESULT=$(readlink -f "$2")
 	    shift;shift;;
 	--logfile)
-	    exec > $(readlink -f "$2");
+	    exec > "$2";
 	    exec 2>&1
 	    PBUILDER_BUILD_LOGFILE=$(readlink -f "$2")
 	    shift;shift;;
@@ -220,7 +220,7 @@ while [ -n "$1" ] ; do
     esac
 done
 
-BUILDING_DSC_FILE=$(readlink -f "$1")
+BUILDING_DSC_FILE=$(readlink -f "$1") || true # ignore failure here
 EXTRACLEANUP=
 UML_EXITCODE=1
 case "${OPERATION}" in
