+2005-08-07  Junichi Uekawa  <dancer@debian.org> + +	* debian/control: allow cdebootstrap dependency. + +	* testsuite/run-test.sh: complicate the process by testing both +	  cdebootstrap and debootstrap. + +	* pbuilder.8: document --debootstrap + +	* pbuilder-checkparams: --debootstrap + +	* pbuilder-modules: --debootstrap + +	* pbuilder-createbuildenv: unset DEBOOTSTRAPSCRIPT instead of setting +	"". The number of parameter given to cdebootstrap changes. +	since DEBOOTSTRAPSCRIPT are not supported by cdebootstrap, +	Giving cdebootstrap this parameter caused it to fail. + +	* pbuilderrc.5: Document DEBOOTSTRAP + +	* pbuilderrc (DEBOOTSTRAP): new option. + +	* pbuilder-createbuildenv (DEBOOTSTRAPSCRIPT): call ${DEBOOTSTRAP} instead of calling debootstrap directly. +

diff --git a/pbuilder-createbuildenv b/pbuilder-createbuildenv
--- a/pbuilder-createbuildenv
+++ b/pbuilder-createbuildenv
@@ -45,8 +45,8 @@ if [ ! -d "$BUILDPLACE" ]; then
 fi
 $TRAP cleanbuildplace exit
 
-echo " -> running debootstrap"
-DEBOOTSTRAPSCRIPT=""
+echo " -> running $DEBOOTSTRAP"
+unset DEBOOTSTRAPSCRIPT
 if [ -n "$HOOKDIR" ]; then
     if [ -f "$HOOKDIR/$DISTRIBUTION" ]; then
 	DEBOOTSTRAPSCRIPT=$(readlink -f $HOOKDIR)"/$DISTRIBUTION"
@@ -54,8 +54,8 @@ if [ -n "$HOOKDIR" ]; then
     fi
 fi
 
-if ! ( cd "$BUILDPLACE" && debootstrap "${DEBOOTSTRAPOPTS[@]}" "$DISTRIBUTION" . "$MIRRORSITE" "$DEBOOTSTRAPSCRIPT" ) ; then
-    echo "pbuilder: debootstrap failed" >&2
+if ! ( cd "$BUILDPLACE" && "${DEBOOTSTRAP}" "${DEBOOTSTRAPOPTS[@]}" "$DISTRIBUTION" . "$MIRRORSITE" $DEBOOTSTRAPSCRIPT ) ; then
+    echo "pbuilder: $DEBOOTSTRAP failed" >&2
     exit 1
 fi
 
