updated some documentation, added more error checking, and some general improvement on the well-being of the package

diff --git a/pbuilder-modules b/pbuilder-modules
--- a/pbuilder-modules
+++ b/pbuilder-modules
@@ -122,8 +122,18 @@ function extractbuildplace () {
     cleanbuildplace
     echo "building the build env"
     echo " -> extracting base.tgz"
-    mkdir -p "$BUILDPLACE"
-    (cd "$BUILDPLACE" && tar xfzp "$BASETGZ")
+    if ! mkdir -p "$BUILDPLACE"; then
+	echo "E: failed to build the directory to chroot"
+	exit 1
+    fi
+    if [ ! -f "$BASETGZ" ]; then
+	echo "E: failed to find $BASETGZ, have you done <pbuilder create> to create your base tarball yet?"
+	exit 1
+    fi
+    if ! (cd "$BUILDPLACE" && tar xfzp "$BASETGZ"); then
+	echo "E: failed to extract $BASETGZ to $BUILDPLACE"
+	exit 1
+    fi
     mountproc
     mkdir -p "$BUILDPLACE/tmp/buildd"
     echo " -> copying local configuration"
