+2002-05-30  Junichi Uekawa  <dancer@debian.org> + +	* pbuilder-modules: add suggestion from david@josefine.at

diff --git a/pbuilder-modules b/pbuilder-modules
--- a/pbuilder-modules
+++ b/pbuilder-modules
@@ -115,6 +115,9 @@ function cleanbuildplace () {
 
 function umountproc_cleanbuildplace () {
     # rolling back to abort.
+    if [ "$?" -ne 0 ]; then
+	echo " -> Aborting with an error";
+    fi
     umountproc
     cleanbuildplace
 }
