some minor fixups for satisfydepends workage. It is getting closer to working state. I think.

diff --git a/pbuilder-buildpackage b/pbuilder-buildpackage
--- a/pbuilder-buildpackage
+++ b/pbuilder-buildpackage
@@ -33,8 +33,11 @@ function copydsc () {
 }
 
 function checkbuilddep () {
-    /usr/lib/pbuilder/pbuilder-satisfydepends --control "$BUILDPLACE/"tmp/buildd/*/debian/control --chroot "$BUILDPLACE"
-    checkbuilddep_internal
+    if ! /usr/lib/pbuilder/pbuilder-satisfydepends --control "$BUILDPLACE/"tmp/buildd/*/debian/control --chroot "$BUILDPLACE" ; then
+	echo "E: pbuilder-satisfydepends failed." >&2
+	saveaptcache_umountproc_cleanbuildplace
+	exit 1
+    fi
     # install extra packages to the chroot
     if [ -n "$EXTRAPACKAGES" ]; then 
 	$CHROOTEXEC usr/bin/apt-get -y install ${EXTRAPACKAGES}
diff --git a/pbuilder-satisfydepends b/pbuilder-satisfydepends
--- a/pbuilder-satisfydepends
+++ b/pbuilder-satisfydepends
@@ -124,8 +124,8 @@ tolower($0) ~ /^'"${BD_REGEXP}"':/   {p=1}
 	fi
       done;
       if [ "$SATISFIED" = "no" ]; then
-	  echo "E: pbuilder: Could not satisfy build-dependency." >&2
-	  saveaptcache_umountproc_cleanbuildplace
+	  echo "E: Could not satisfy build-dependency." >&2
+	  #saveaptcache_umountproc_cleanbuildplace
 	  exit 1
       fi
     done;
@@ -164,7 +164,7 @@ tolower($0) ~ /^'"${BC_REGEXP}"':/   {p=1}
       if $CHROOTEXEC /usr/bin/dpkg -s $(echo "$INSTALLPKG" | tr "/" " " | awk '{print $1}') 2>&1 | grep ^Package: > /dev/null; then
 	  if ! $CHROOTEXEC /usr/bin/apt-get -y remove ${CURRENTREALPKGNAME} ; then
 	      echo "E: Could not satisfy build-conflicts" >&2
-	      saveaptcache_umountproc_cleanbuildplace
+	      #saveaptcache_umountproc_cleanbuildplace
 	      exit 1
 	  fi
       else
@@ -218,14 +218,14 @@ while [ -n "$1" ]; do
 	    shift
 	    ;;
 	--echo)
-	    CHROOTEXEC="echo "
+	    CHROOTEXEC="echo $CHROOTEXEC"
 	    shift
 	    ;;
 	--force-version)
 	    FORCEVERSION="yes"
 	    shift;
 	    ;;
-	--help|-h)
+	--help|-h|*)
 	    print_help
 	    exit 1
 	    ;;
