commit change

diff --git a/pbuilder-modules b/pbuilder-modules
--- a/pbuilder-modules
+++ b/pbuilder-modules
@@ -107,6 +107,9 @@ function mountproc () {
 }
 
 function cleanbuildplace () {
+    if [ "$?" -ne 0 ]; then
+	echo " -> Aborting with an error";
+    fi
     if [ -d "$BUILDPLACE" ]; then 
 	echo " -> cleaning the build env "
 	rm -rf "$BUILDPLACE"
