+ +	* pbuilder-modules (create_basetgz): new function +	add file locking +	(extractbuildplace) add file locking. + +	* pbuilder-updatebuildenv: use create_basetgz + +	* pbuilder-createbuildenv (DEBOOTSTRAPSCRIPT): make error handling more +	fine-grained, and add more handling for error cases. +	(create_basetgz): move function over to -modules. +	and use it. +

diff --git a/pbuilder-modules b/pbuilder-modules
--- a/pbuilder-modules
+++ b/pbuilder-modules
@@ -184,14 +184,22 @@ function extractbuildplace () {
 	    echo "E: failed to build the directory to chroot"
 	    exit 1
 	fi
+	while [ -f "${BASETGZ}.tmp" ]; do
+	    echo " -> Someone else has lock over ${BASETGZ}.tmp, waiting"
+	    sleep 10s
+	done
+	touch "${BASETGZ}.tmp"
 	if [ ! -f "$BASETGZ" ]; then
 	    echo "E: failed to find $BASETGZ, have you done <pbuilder create> to create your base tarball yet?"
+	    rm -f "${BASETGZ}.tmp"
 	    exit 1
 	fi
 	if ! (cd "$BUILDPLACE" && tar xfzp "$BASETGZ"); then
 	    echo "E: failed to extract $BASETGZ to $BUILDPLACE"
+	    rm -f "${BASETGZ}.tmp"
 	    exit 1
 	fi
+	rm -f "${BASETGZ}.tmp"
 	echo " -> creating local configuration"
 	hostname -f > "$BUILDPLACE/etc/mailname"
     fi
@@ -237,6 +245,27 @@ function save_aptcache() {
 	    fi
 	done
     fi
+}
+
+function create_basetgz() {
+    # create base.tgz
+    echo " -> creating base.tgz"
+    ( 
+	if ! cd "$BUILDPLACE"; then
+	    echo "Error: unexpected error in chdir to $BUILDPLACE" >&2
+	    exit 1;
+	fi
+	while test -f "${BASETGZ}.tmp"; do
+	    echo "  -> Someone else has lock over ${BASETGZ}.tmp, waiting"
+	    sleep 10s
+	done
+	if ! tar cfz "${BASETGZ}.tmp" * ; then
+	    echo " -> failed building base.tgz"
+	    rm -f "${BASETGZ}.tmp"
+	    exit 1;
+	fi
+	mv "${BASETGZ}.tmp" "${BASETGZ}"
+    )
 }
 
 #required for some packages to install...
