+	* pbuilder-user-mode-linux: add fsck

diff --git a/pbuilder-user-mode-linux b/pbuilder-user-mode-linux
--- a/pbuilder-user-mode-linux
+++ b/pbuilder-user-mode-linux
@@ -64,6 +64,10 @@ ${UML_DEBUGMODE}
 
 mount -t proc /proc /proc
 mount -t tmpfs /tmp /tmp
+if ! fsck /dev/ubd/1; then
+  echo "E: Failed to fsck /dev/ubd/1"
+  exit 1
+fi
 if ! mount -t ext2 /dev/ubd/1 ${UML_CHROOT_MOUNTPOINT}; then
   echo "E: Cannot mount /dev/ubd/1, is UML root image accessible as current user?"
   exit 1
