+2004-10-31  Junichi Uekawa  <dancer@debian.org> + +	* Documentation/pbuilder-doc.xml (PBUILDER_UML_IMAGE): add notes on +	BUILRESULTUID and SUDO interaction. + +	* pbuilder-buildpackage (PACKAGENAME): move around buildresult dir creation before pkgname logfile creation. + +	* pbuilder.8: add documentation for --save-after-login/exec option. + +	* pbuilder: execute and login with --save-after-login/exec option. + +	* pbuilder-user-mode-linux.1: add notes that uml-nocow is effective for exec and login. + +	* pbuilder-uml-checkparams (UML_SAVE_AFTER_LOGIN): add UML_NOCOW for exec + +	* pbuilder-checkparams (SAVE_AFTER_LOGIN): --save-after-login/exec command-option. + +	* pdebuild-user-mode-linux.1: add notes that the option will override +	pbuilder option. + +	* pdebuild.1: add notes that the option will override pbuilder option + +	* pdebuild-user-mode-linux: ditto. + +	* pdebuild: override --debbbuildopts in pbuilder option when DEBBUILDOPTS is available and for non-internal mode. +

diff --git a/pbuilder b/pbuilder
--- a/pbuilder
+++ b/pbuilder
@@ -65,6 +65,19 @@ File extracted to: $BUILDPLACE
 	fi
 	executehooks "F"
 	chroot "$BUILDPLACE" bin/bash
+
+	# saving the place afterwards
+	if [ "${SAVE_AFTER_LOGIN}" = "yes" ]; then
+	    if [ "${INTERNAL_BUILD_UML}" = "yes" ]; then
+		echo "E: Invalid combination of internal-build-uml and save-after-login flags"
+	    else
+		echo " -> Saving the results, modifications to this session will persist"
+		unloadhooks
+		umountproc
+		trap cleanbuildplace exit
+		create_basetgz
+	    fi
+	fi
 	;;
     execute)
 	# try to execute arbitrary program.
@@ -78,13 +91,29 @@ File extracted to: $BUILDPLACE
 	    exit 1;
 	fi;
 	extractbuildplace
+
 	trap umountproc_cleanbuildplace exit
+
 	loadhooks
 	RUNNAME="$BUILDPLACE/run"
 	cat "$EXECPROGRAM" > "$RUNNAME"
 	chmod a+x "$RUNNAME"
 	executehooks "F"
 	chroot "$BUILDPLACE" /run "$@"
+
+
+	# saving the place afterwards
+	if [ "${SAVE_AFTER_LOGIN}" = "yes" ]; then
+	    if [ "${INTERNAL_BUILD_UML}" = "yes" ]; then
+		echo "E: Invalid combination of internal-build-uml and save-after-login flags"
+	    else
+		echo " -> Saving the results, modifications to this session will persist"
+		unloadhooks
+		umountproc
+		trap cleanbuildplace exit
+		create_basetgz
+	    fi
+	fi
 	;;
     dumpconfig)
 	shift
