Changes are done to pbuilder-buildpackage to fix outstanding bugs.

diff --git a/pbuilder-buildpackage b/pbuilder-buildpackage
--- a/pbuilder-buildpackage
+++ b/pbuilder-buildpackage
@@ -66,12 +66,16 @@ function checkbuilddep_archdeps () {
 
 function checkbuilddep_provides () {
     local PACKAGENAME="$1"
+    # PROVIDED needs to be used outside of this function.
     PROVIDED=$($CHROOTEXEC usr/bin/apt-cache showpkg $PACKAGENAME | awk '{p=0}/^Reverse Provides:/,/^$/{p=1}{if(p && ($0 !~ "Reverse Provides:")){PACKAGE=$1}} END{print PACKAGE}')
 }
 
 function checkbuilddep_internal () {
 # Use this function to fulfill the dependency (almost)
     local ARCH=$(dpkg --print-architecture)
+    local INSTALLPKG
+    local INSTALLPKGMULTI
+    local CURRENTREALPKGNAME
     echo " -> Attempting to parse the build-deps by myself"
     for INSTALLPKGMULTI in $(cat "$BUILDPLACE/"tmp/buildd/*/debian/control | \
 	tr 'A-Z' 'a-z' | \
@@ -79,7 +83,7 @@ function checkbuilddep_internal () {
 	sed 's/^[^:]*: //' | \
 	tr " " "/" | \
 	awk 'BEGIN{RS=","} {print}'); do
-      echo " -> Considering "$(echo $INSTALLPKGMULTI | tr "/" " " | awk '{print $1}' )
+      echo " -> Considering "$(echo $INSTALLPKGMULTI | tr "/" " " | awk '{print $0}' )
       SATISFIED="no"
       for INSTALLPKG in $(echo "$INSTALLPKGMULTI" | \
 	  awk 'BEGIN{RS="|"} {print}'); do
@@ -99,14 +103,15 @@ function checkbuilddep_internal () {
 	      continue;
 	    fi
 	fi
-	echo " -> Installing "$(echo "$INSTALLPKG" | tr "/" " " | awk '{print $1}')
+	CURRENTREALPKGNAME=$(echo "$INSTALLPKG" | sed 's/[[/(].*//')
+	echo " -> Installing "${CURRENTREALPKGNAME}
 
-	if $CHROOTEXEC usr/bin/apt-get -y install $(echo "$INSTALLPKG" | tr "/" " " | awk '{print $1}'); then
+	if $CHROOTEXEC usr/bin/apt-get -y install ${CURRENTREALPKGNAME}; then
 	    SATISFIED="yes"
 	else
 	    # package could not be found. -- looking for alternative.
 	    PROVIDED=""
-	    checkbuilddep_provides $(echo "$INSTALLPKG" | tr "/" " " | awk '{print $1}')
+	    checkbuilddep_provides ${CURRENTREALPKGNAME}
 	    if [ -n "$PROVIDED" ]; then
 		# something provides this package
 		echo "   -> Installing $PROVIDED to satisfy the dependency "
@@ -120,7 +125,7 @@ function checkbuilddep_internal () {
 	fi
       done;
       if [ "$SATISFIED" = "no" ]; then
-	  echo Could not satisfy build-dependency.
+	  echo "Could not satisfy build-dependency." >&2
 	  umountproc_cleanbuildplace
 	  exit 1
       fi
@@ -133,7 +138,9 @@ function checkbuilddep_internal () {
 	sed 's/^[^:]*: //' | \
 	tr " " "/" | \
 	awk 'BEGIN{RS=","} {print}'); do
-      echo " -> Considering "$(echo $INSTALLPKG | tr "/" " " | awk '{print $1}' )
+      CURRENTREALPKGNAME=$(echo "$INSTALLPKG" | sed 's/[[/(].*//')
+      echo " -> Considering "${CURRENTREALPKGNAME}
+      
       if echo "$INSTALLPKG" | grep '\[' > /dev/null ; then
 	  # this package has arch-conflicts.
 	  if checkbuilddep_archdeps "$INSTALLPKG" "$ARCH"; then
@@ -143,7 +150,7 @@ function checkbuilddep_internal () {
       fi
       if echo "$INSTALLPKG" | grep '[(]' > /dev/null ; then
 	  # this package has version-conflicts
-	  if ! checkbuilddep_versiondeps $(echo "$INSTALLPKG" | tr "/" " " | awk '{print $1}') \
+	  if ! checkbuilddep_versiondeps ${CURRENTREALPKGNAME} \
 		$(echo "$INSTALLPKG" | tr "/" " " | sed 's/^.*(\(<<\|<=\|>=\|=\|<\|>>\|>\)[ ]*\(.*\)).*$/\1/') \
 		$(echo "$INSTALLPKG" | tr "/" " " | sed 's/^.*(\(<<\|<=\|>=\|=\|<\|>>\|>\)[ ]*\(.*\)).*$/\2/'); then
 	      echo "I: Satisfies version, not trying"
@@ -153,7 +160,7 @@ function checkbuilddep_internal () {
 
       # if package exists, remove it.
       if $CHROOTEXEC usr/bin/dpkg -s $(echo "$INSTALLPKG" | tr "/" " " | awk '{print $1}') 2>&1 | grep ^Package: > /dev/null; then
-	  if ! $CHROOTEXEC usr/bin/apt-get -y remove $(echo "$INSTALLPKG" | tr "/" " " | awk '{print $1}') ; then
+	  if ! $CHROOTEXEC usr/bin/apt-get -y remove ${CURRENTREALPKGNAME} ; then
 	      echo "E: Could not satisfy build-conflicts" >&2
 	      umountproc_cleanbuildplace
 	      exit 1
@@ -165,7 +172,7 @@ function checkbuilddep_internal () {
 }
 
 function checkbuilddep () {
-    checkbuilddep_internal;
+    checkbuilddep_internal
 }
 
 function echobacktime () {
