* pbuilder-user-mode-linux.1: update doc.
	* pbuilder-user-mode-linux (UML_DEBUGMODE): error check if BUILDPLACE
	is user-accessible.

diff --git a/pbuilder-user-mode-linux b/pbuilder-user-mode-linux
--- a/pbuilder-user-mode-linux
+++ b/pbuilder-user-mode-linux
@@ -245,6 +245,12 @@ while [ -n "$1" ] ; do
     esac
 done
 
+
+if ! touch "${BUILDPLACE}/touch" ; then
+    echo "E: Cannot touch ${BUILDPLACE}/touch, check BUILDPLACE" >&2
+    exit 1
+fi
+
 BUILDING_DSC_FILE=$(readlink -f "$1") || true # ignore failure here
 EXTRACLEANUP=
 UML_EXITCODE=1
