making ready for uploading to Debian archive, changing depends line to debootstrap with versioned depends. Re-tabbing, extactbuildplace function is created to move common code out from create and build. added an error message for unknown parameter option. added a TAGS target to the makefile to make ETAGS work.

diff --git a/pbuilder-buildpackage b/pbuilder-buildpackage
--- a/pbuilder-buildpackage
+++ b/pbuilder-buildpackage
@@ -12,17 +12,22 @@ function copydsc () {
       $(echo "$DSCFILE" | sed 's/\(.*\)-[^-.]*\.dsc$/\1/').orig.tar.gz ; do
         cp "$FILE" "$TARGET" ;
     done
-
 }
 
 function checkbuilddep () {
-    for INSTALLPKG in $($CHROOTEXEC bin/sh -c "(cd tmp/buildd/*/; dpkg-checkbuilddeps)" 2>&1 |grep "^dpkg-checkbuilddeps: Unmet build dependencies: " | sed 's/^[^:]*:[^:]*: \(.*\)$/\1/' | awk 'BEGIN{RS=", "} /^([^([]*)/{print $1}'); do
-	echo " -> Installing $INSTALLPKG"
-	$CHROOTEXEC usr/bin/apt-get -y install "$INSTALLPKG"
+    for INSTALLPKG in $($CHROOTEXEC bin/sh -c "(cd tmp/buildd/*/; dpkg-checkbuilddeps)" 2>&1 | \
+	grep "^dpkg-checkbuilddeps: Unmet build dependencies: " | \
+	sed 's/^[^:]*:[^:]*: \(.*\)$/\1/' | \
+	awk 'BEGIN{RS=", "} /^([^([]*)/{print $1}'); do
+      echo " -> Installing $INSTALLPKG"
+      $CHROOTEXEC usr/bin/apt-get -y install "$INSTALLPKG"
     done;
-    for REMOVEPKG in $($CHROOTEXEC bin/sh -c "(cd tmp/buildd/*/; dpkg-checkbuilddeps)" 2>&1 |grep "^dpkg-checkbuilddeps: Build conflicts: " | sed 's/^[^:]*:[^:]*: \(.*\)$/\1/' | awk 'BEGIN{RS=", "} /^([^([]*)/{print $1}'); do
-	echo " -> Removing $REMOVEPKG"
-	$CHROOTEXEC usr/bin/apt-get -y remove "$REMOVEPKG"
+    for REMOVEPKG in $($CHROOTEXEC bin/sh -c "(cd tmp/buildd/*/; dpkg-checkbuilddeps)" 2>&1 | \
+	grep "^dpkg-checkbuilddeps: Build conflicts: " | \
+	sed 's/^[^:]*:[^:]*: \(.*\)$/\1/' | \
+	awk 'BEGIN{RS=", "} /^([^([]*)/{print $1}'); do
+      echo " -> Removing $REMOVEPKG"
+      $CHROOTEXEC usr/bin/apt-get -y remove "$REMOVEPKG"
     done;
 }
 
@@ -31,22 +36,12 @@ function checkbuilddep () {
 PACKAGENAME="$1"
 CHROOTEXEC="chroot $BUILDPLACE "
 
-
-
 if [ ! -f "$PACKAGENAME" ]; then
-  echo "Command line parameter [$PACKAGENAME] is not a valid .dsc file name" >&2
-  exit 1;
+    echo "Command line parameter [$PACKAGENAME] is not a valid .dsc file name" >&2
+    exit 1;
 fi;
 
-cleanbuildplace
-echo "building the build env"
-mkdir -p "$BUILDPLACE"
-(
- cd "$BUILDPLACE"
- tar xfzp "$BASETGZ"
- mkdir -p "$BUILDPLACE/tmp/buildd"
- )
-mountproc
+extractbuildplace 
 
 echo Copying source file
 copydsc "$PACKAGENAME" "$BUILDPLACE/tmp/buildd"
@@ -56,15 +51,17 @@ echo Installing the build-deps
 checkbuilddep
 echo Building the package
 $CHROOTEXEC /bin/sh -c "(cd tmp/buildd/*/; dpkg-buildpackage)"
+
 umountproc
 
 test -n "$BUILDRESULT" && (
-  mkdir -p "$BUILDRESULT"
-  if [ -d "$BUILDRESULT" ]; then
-    cp "$BUILDPLACE"/tmp/buildd/* "$BUILDRESULT"
-  else
-    echo "Error: BUILDRESULT=[$BUILDRESULT] and is not a directory." >&2
-  fi
+    mkdir -p "$BUILDRESULT"
+    if [ -d "$BUILDRESULT" ]; then
+	cp "$BUILDPLACE"/tmp/buildd/* "$BUILDRESULT"
+    else
+	echo "Error: BUILDRESULT=[$BUILDRESULT] and is not a directory." >&2
+    fi
 )
+
 cleanbuildplace
 
diff --git a/pbuilder-checkparams b/pbuilder-checkparams
--- a/pbuilder-checkparams
+++ b/pbuilder-checkparams
@@ -7,34 +7,34 @@
 BASEBUILDPLACE="$BUILDPLACE"
 BUILDPLACE="$BUILDPLACE/$$"
 
-while [ -n $1 ]; do
-  case "$1" in 
-    --basetgz) 
-      BASETGZ=$(readlink -f "$2");
-      shift; shift;
-      ;;
-    --buildplace)
-      BUILDPLACE=$(readlink -f "$2");
-      shift; shift;
-      ;;
-    --mirror)
-      MIRROR="$2";
-      shift; shift;
-      ;;
-    --http-proxy)
-      export http_proxy="$2";
-      shift; shift;
-      ;;
-    --distribution)
-      DISTRIBUTION="$2";
-      shift; shift;
-      ;;
-    --buildresult)
-      BUILDRESULT=$(readlink -f "$2");
-      shift; shift;
-      ;;
-    --help)
-      cat <<EOF
+while [ -n "$1" ]; do 
+    case "$1" in 
+	--basetgz) 
+	    BASETGZ=$(readlink -f "$2");
+	    shift; shift;
+	    ;;
+	--buildplace)
+	    BUILDPLACE=$(readlink -f "$2");
+	    shift; shift;
+	    ;;
+	--mirror)
+	    MIRROR="$2";
+	    shift; shift;
+	    ;;
+	--http-proxy)
+	    export http_proxy="$2";
+	    shift; shift;
+	    ;;
+	--distribution)
+	    DISTRIBUTION="$2";
+	    shift; shift;
+	    ;;
+	--buildresult)
+	    BUILDRESULT=$(readlink -f "$2");
+	    shift; shift;
+	    ;;
+	--help)
+	    cat <<EOF
 Command Line Options:
  --basetgz [base.tgz location]
  --buildplace [location of build]
@@ -43,11 +43,15 @@ Command Line Options:
  --distribution [distribution(woody/sid)]
  --buildresult [location-to-copy-build-result]
 EOF
-      exit 1;
-      ;;
-    *)
-      break;
-      ;;
+	    exit 1;
+	    ;;
+	--*)
+	    echo "Error: Unknown option [$1] was specified " >&2 
+	    exit 1;
+	    ;;
+	*)
+	    break;
+	    ;;
   esac
 done
 
diff --git a/pbuilder-createbuildenv b/pbuilder-createbuildenv
--- a/pbuilder-createbuildenv
+++ b/pbuilder-createbuildenv
@@ -1,29 +1,34 @@
 #! /bin/bash
-#necessary for installs.
+# Creating the build environment with debootstrap.
 
 . /usr/lib/pbuilder/pbuilder-checkparams
 . /usr/lib/pbuilder/pbuilder-modules
 
 CHROOTEXEC="chroot $BUILDPLACE "
 if [ -z "$DISTRIBUTION" ]; then
-  DISTRIBUTION=woody
+    DISTRIBUTION=woody
 fi
 echo "Distribution is $DISTRIBUTION."
 
 cleanbuildplace
 
-echo "building the build env"
+echo "Building the build environment"
 mkdir -p "$BUILDPLACE"
+if [ ! -d "$BUILDPLACE" ]; then
+    echo "pbuilder: Could not make directory [$BUILDPLACE]" >&2
+    exit 1
+fi
 mountproc
 echo " -> running debootstrap"
-( cd "$BUILDPLACE"; debootstrap "$DISTRIBUTION" . )
+( cd "$BUILDPLACE" && debootstrap "$DISTRIBUTION" . )
+echo " -> debootstrap finished"
 mkdir -p "$BUILDPLACE/tmp/buildd"
 echo " -> copying local configuration"
 for a in passwd hosts hostname resolv.conf apt; do 
-  cp -r /etc/$a "$BUILDPLACE/etc/";
+    cp -r /etc/$a "$BUILDPLACE/etc/";
 done
 
-echo "Installing apt-lines"
+echo " -> installing apt-lines"
 cat > "$BUILDPLACE/etc/apt/sources.list" << EOF
 deb $MIRRORSITE $DISTRIBUTION main contrib non-free
 deb-src $MIRRORSITE $DISTRIBUTION main contrib non-free
@@ -38,6 +43,6 @@ $CHROOTEXEC /usr/bin/apt-get -y install build-essential dpkg-dev apt $EXTRAPACKA
 $CHROOTEXEC /usr/bin/apt-get clean
 umountproc
 echo " -> creating base.tgz"
-( cd "$BUILDPLACE" ; tar cfz "$BASETGZ" * )
+( cd "$BUILDPLACE" && tar cfz "$BASETGZ" * || echo " -> failed building base.tgz")
 cleanbuildplace
 
