created a proper postinst which takes into account the different parameters which are used when calling it

diff --git a/debian/pbuilder.postinst b/debian/pbuilder.postinst
--- a/debian/pbuilder.postinst
+++ b/debian/pbuilder.postinst
@@ -1,20 +1,60 @@
 #!/bin/sh
+# postinst script for pbuilder
+#
+# see: dh_installdeb(1)
 
 . /usr/share/debconf/confmodule
 
-CONFFILE=/etc/pbuilderrc
+set -e
 
-db_get pbuilder/mirrorsite
-MIRRORSITE="$RET"
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <postinst> `abort-remove'
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
 
-if [ "$MIRRORSITE" = "_" ]
-then
-    MIRRORSITE=$(grep -E '^deb ' /etc/apt/sources.list | head -n 1 | awk '{print $2;}')
-    db_set pbuilder/mirrorsite "$MIRRORSITE"
-    db_input medium pbuilder/mirrorsite
-    db_go
-fi
 
-TMPFILE=`mktemp`
-cat "$CONFFILE" | sed "s#MIRRORSITE=.*\$#MIRRORSITE=$MIRRORSITE#" > "$TMPFILE" && mv "$TMPFILE" "$CONFFILE"
+case "$1" in
+    configure)
+
+        CONFFILE=/etc/pbuilderrc
+
+        db_get pbuilder/mirrorsite
+        MIRRORSITE="$RET"
+
+        if [ "$MIRRORSITE" = "_" ]
+        then
+            MIRRORSITE=$(grep -E '^deb ' /etc/apt/sources.list | head -n 1 | awk '{print $2;}')
+            db_set pbuilder/mirrorsite "$MIRRORSITE"
+            db_input medium pbuilder/mirrorsite
+            db_go
+        fi
+
+        TMPFILE=`mktemp`
+        cat "$CONFFILE" | sed "s#MIRRORSITE=.*\$#MIRRORSITE=$MIRRORSITE#" > "$TMPFILE" && mv "$TMPFILE" "$CONFFILE"
+
+    ;;
+
+    abort-upgrade|abort-remove|abort-deconfigure)
+    ;;
+
+    *)
+        echo "postinst called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
+#DEBHELPER#
+
+exit 0
+
 
