Misc enhancements to sample lintian hook
examples/B90lintian: Run lintian as pbuilder and not root and show how
to not fail the build if lintian fails.

diff --git a/examples/B90lintian b/examples/B90lintian
--- a/examples/B90lintian
+++ b/examples/B90lintian
@@ -1,6 +1,18 @@
-#!/bin/bash
-# example file to be used with --hookdir
-#
-# run lintian on generated deb files
-apt-get install -y --force-yes lintian
-lintian /tmp/buildd/*.deb
+#!/bin/sh
+
+set -e
+
+install_packages() {
+    apt-get -y --force-yes install "$@"
+}
+
+install_packages lintian
+
+echo "+++ lintian output +++"
+
+su -c "lintian -I --show-overrides /tmp/buildd/*.changes" - pbuilder
+# use this version if you don't want lintian to fail the build
+#su -c "lintian -I --show-overrides /tmp/buildd/*.changes; :" - pbuilder
+
+echo "+++ end of lintian output +++"
+
