improve B92test-pkg: Allow satisfying dependency inside chroot.
This allows easier testing when package is new and not already
packaged in Debian.

diff --git a/examples/B92test-pkg b/examples/B92test-pkg
--- a/examples/B92test-pkg
+++ b/examples/B92test-pkg
@@ -8,13 +8,15 @@
 set -e 
 
 echo "Installing the prerequisites"
+# ignore the failures since they are not the prime interest
 for PKG in $(ls /tmp/buildd/*.deb | sed -e's,.*/,,;s,_.*,,' ); do
     apt-get install -y --force-yes "$PKG" || true 
     apt-get remove -y "$PKG" || true 
 done
-# ignore the failures since they are not the prime interest
 
-dpkg -i /tmp/buildd/*.deb
+# install the single package, then try to satisfy dependencies.
+dpkg -i /tmp/buildd/*.deb || true
+apt-get install -y -f --force-yes
 
 if chmod a+x /tmp/buildd/*/debian/pbuilder-test/*; then
     :
